import { GET_LIST_BANNER } from "../types/Type";

const initialState = {
  listBanner: [],
  listFilms: [
    {
      "maPhim": 10667,
      "tenPhim": "MAIKA - CÔ BÉ ĐẾN TỪ HÀNH TINH KHÁC",
      "biDanh": "maika-co-be-den-tu-hanh-tinh-khac",
      "trailer": "https://youtu.be/mOH-VKJBsh8",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/maika-co-be-den-tu-hanh-tinh-khac_gp01.jpg",
      "moTa": "\"Maika - Cô bé đến từ hành tinh khác\" (đạo diễn Hàm Trần) gợi nhớ tuổi thơ với hình ảnh đẹp, cốt truyện cảm động về tình bạn, gia đình. Ra mắt nhân dịp Quốc tế Thiếu nhi 1/6, tác phẩm lấy cảm hứng từ Maika, cô bé từ trên trời rơi xuống - phim truyền hình Tiệp Khắc chiếu ở Việt Nam những năm 1980.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-27T00:00:00",
      "danhGia": 8,
      "hot": true,
      "dangChieu": false,
      "sapChieu": true
    },
    {
      "maPhim": 10558,
      "tenPhim": "LIÊN MINH SIÊU THÚ DC 23",
      "biDanh": "lien-minh-sieu-thu-dc-23",
      "trailer": "https://www.youtube.com/watch?v=L2umMe5uRnk",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/lien-minh-sieu-thu-dc_gp01.jpg",
      "moTa": "Trong “Liên Minh Siêu Thú DC”, Siêu Cún Krypto và Superman là cặp bài trùng không thể tách rời, cùng sở hữu những siêu năng lực tương tự và cùng nhau chiến đấu chống lại tội phạm tại thành phố Metropolis. Khi Superman và những thành viên của Liên Minh Công Lý bị bắt cóc, Krypto phải thuyết phục cậu chàng Ace luộm thuộm, nàng Heo PB, Rùa Merton và Sóc Chip khai phá những sức mạnh tiềm ẩn và cùng nhau giải cứu các siêu anh hùng. “Liên Minh Siêu Thú DC” có sự góp giọng của bộ đôi ngôi sao nổi tiếng bậc nhất Hollywood Dwayne Johnson (lồng tiếng cho Siêu cún Krypto) và Kevin Hart (Superman). Đặc biệt, tài tử Keanu Reeves sẽ đảm nhận những câu thoại chất lừ đến từ Batman.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-10-24T19:07:24.247",
      "danhGia": 10,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
    {
      "maPhim": 10603,
      "tenPhim": "the waliking dead",
      "biDanh": "the-waliking-dead",
      "trailer": "https://www.youtube.com/watch?v=sfAc2U20uyg",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/the-waliking-dead_gp01.jpg",
      "moTa": "Xác Sống 11 (The Walking Dead Season 11) là mùa cuối cùng của một loạt phim truyền hình Mỹ thuộc thể loại kinh dị và hậu tận thế của kênh AMC, dựa trên seri truyện tranh cùng tên do Robert Kirkman, Tony Moore và Charlie Adlard sáng tạo. The Walking Dead - series khai sáng cho kỷ nguyên zombie trên màn ảnh nhỏ chuẩn bị đi tới hồi kết.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-14T00:00:00",
      "danhGia": 9,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
    {
      "maPhim": 10604,
      "tenPhim": "Bleach",
      "biDanh": "bleach",
      "trailer": "https://youtu.be/oblZrnM9p6A?t=5",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/bleach_gp01.png",
      "moTa": "Ichigo Kurosaki là một thiếu niên có khả năng nhìn thấy linh hồn. Cuộc sống của anh thay đổi nhanh chóng bởi sự xuất hiện đột ngột của một Soul Reaper - một trong những người điều chỉnh dòng chảy của linh hồn giữa thế giới con người và thế giới bên kia, tên là Kuchiki Rukia, người đến thế giới con người để tìm diệt Hollow, một linh hồn lạc lối rất nguy hiểm. Khi Rukia bị thương nặng vì bảo vệ Ichigo khỏi Hollow, cô cố gắng chuyển một nửa trong số năng lượng reiatsu (sức mạnh linh hồn) của cô cho Ichigo để anh có thể đánh bại Hollow. Tuy nhiên, Ichigo lấy gần như tất cả năng lượng của Rukia và biến đổi thành một Soul Reaper, cho phép anh đánh bại Hollow dễ dàng.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-14T00:00:00",
      "danhGia": 8,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
    {
      "maPhim": 10610,
      "tenPhim": "Moon Knight ",
      "biDanh": "moon-knight",
      "trailer": "https://youtu.be/x7Krla_UxRg",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/moon-knight_gp01.jpeg",
      "moTa": "Steven Grant discovers he's been granted the powers of an Egyptian moon god. But he soon finds out that these newfound powers can be both a blessing and a curse to his troubled life.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-19T18:37:09.357",
      "danhGia": 9,
      "hot": true,
      "dangChieu": true,
      "sapChieu": false
    },
    {
      "maPhim": 10645,
      "tenPhim": "Game of Throne",
      "biDanh": "game-of-throne",
      "trailer": "https://youtu.be/KPLWWIOCOOQ",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/game-of-throne_gp01.jpg",
      "moTa": "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-27T19:54:46.097",
      "danhGia": 9,
      "hot": true,
      "dangChieu": true,
      "sapChieu": false
    },
    {
      "maPhim": 10667,
      "tenPhim": "MAIKA - CÔ BÉ ĐẾN TỪ HÀNH TINH KHÁC",
      "biDanh": "maika-co-be-den-tu-hanh-tinh-khac",
      "trailer": "https://youtu.be/mOH-VKJBsh8",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/maika-co-be-den-tu-hanh-tinh-khac_gp01.jpg",
      "moTa": "\"Maika - Cô bé đến từ hành tinh khác\" (đạo diễn Hàm Trần) gợi nhớ tuổi thơ với hình ảnh đẹp, cốt truyện cảm động về tình bạn, gia đình. Ra mắt nhân dịp Quốc tế Thiếu nhi 1/6, tác phẩm lấy cảm hứng từ Maika, cô bé từ trên trời rơi xuống - phim truyền hình Tiệp Khắc chiếu ở Việt Nam những năm 1980.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-27T00:00:00",
      "danhGia": 8,
      "hot": true,
      "dangChieu": false,
      "sapChieu": true
    },
    {
      "maPhim": 10610,
      "tenPhim": "Moon Knight ",
      "biDanh": "moon-knight",
      "trailer": "https://youtu.be/x7Krla_UxRg",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/moon-knight_gp01.jpeg",
      "moTa": "Steven Grant discovers he's been granted the powers of an Egyptian moon god. But he soon finds out that these newfound powers can be both a blessing and a curse to his troubled life.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-19T18:37:09.357",
      "danhGia": 9,
      "hot": true,
      "dangChieu": true,
      "sapChieu": false
    },
    {
      "maPhim": 10645,
      "tenPhim": "Game of Throne",
      "biDanh": "game-of-throne",
      "trailer": "https://youtu.be/KPLWWIOCOOQ",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/game-of-throne_gp01.jpg",
      "moTa": "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-27T19:54:46.097",
      "danhGia": 9,
      "hot": true,
      "dangChieu": true,
      "sapChieu": false
    },
    {
      "maPhim": 10558,
      "tenPhim": "LIÊN MINH SIÊU THÚ DC 23",
      "biDanh": "lien-minh-sieu-thu-dc-23",
      "trailer": "https://www.youtube.com/watch?v=L2umMe5uRnk",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/lien-minh-sieu-thu-dc_gp01.jpg",
      "moTa": "Trong “Liên Minh Siêu Thú DC”, Siêu Cún Krypto và Superman là cặp bài trùng không thể tách rời, cùng sở hữu những siêu năng lực tương tự và cùng nhau chiến đấu chống lại tội phạm tại thành phố Metropolis. Khi Superman và những thành viên của Liên Minh Công Lý bị bắt cóc, Krypto phải thuyết phục cậu chàng Ace luộm thuộm, nàng Heo PB, Rùa Merton và Sóc Chip khai phá những sức mạnh tiềm ẩn và cùng nhau giải cứu các siêu anh hùng. “Liên Minh Siêu Thú DC” có sự góp giọng của bộ đôi ngôi sao nổi tiếng bậc nhất Hollywood Dwayne Johnson (lồng tiếng cho Siêu cún Krypto) và Kevin Hart (Superman). Đặc biệt, tài tử Keanu Reeves sẽ đảm nhận những câu thoại chất lừ đến từ Batman.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-10-24T19:07:24.247",
      "danhGia": 10,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
    {
      "maPhim": 10603,
      "tenPhim": "the waliking dead",
      "biDanh": "the-waliking-dead",
      "trailer": "https://www.youtube.com/watch?v=sfAc2U20uyg",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/the-waliking-dead_gp01.jpg",
      "moTa": "Xác Sống 11 (The Walking Dead Season 11) là mùa cuối cùng của một loạt phim truyền hình Mỹ thuộc thể loại kinh dị và hậu tận thế của kênh AMC, dựa trên seri truyện tranh cùng tên do Robert Kirkman, Tony Moore và Charlie Adlard sáng tạo. The Walking Dead - series khai sáng cho kỷ nguyên zombie trên màn ảnh nhỏ chuẩn bị đi tới hồi kết.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-14T00:00:00",
      "danhGia": 9,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
    {
      "maPhim": 10558,
      "tenPhim": "LIÊN MINH SIÊU THÚ DC 23",
      "biDanh": "lien-minh-sieu-thu-dc-23",
      "trailer": "https://www.youtube.com/watch?v=L2umMe5uRnk",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/lien-minh-sieu-thu-dc_gp01.jpg",
      "moTa": "Trong “Liên Minh Siêu Thú DC”, Siêu Cún Krypto và Superman là cặp bài trùng không thể tách rời, cùng sở hữu những siêu năng lực tương tự và cùng nhau chiến đấu chống lại tội phạm tại thành phố Metropolis. Khi Superman và những thành viên của Liên Minh Công Lý bị bắt cóc, Krypto phải thuyết phục cậu chàng Ace luộm thuộm, nàng Heo PB, Rùa Merton và Sóc Chip khai phá những sức mạnh tiềm ẩn và cùng nhau giải cứu các siêu anh hùng. “Liên Minh Siêu Thú DC” có sự góp giọng của bộ đôi ngôi sao nổi tiếng bậc nhất Hollywood Dwayne Johnson (lồng tiếng cho Siêu cún Krypto) và Kevin Hart (Superman). Đặc biệt, tài tử Keanu Reeves sẽ đảm nhận những câu thoại chất lừ đến từ Batman.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-10-24T19:07:24.247",
      "danhGia": 10,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
    {
      "maPhim": 10603,
      "tenPhim": "the waliking dead",
      "biDanh": "the-waliking-dead",
      "trailer": "https://www.youtube.com/watch?v=sfAc2U20uyg",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/the-waliking-dead_gp01.jpg",
      "moTa": "Xác Sống 11 (The Walking Dead Season 11) là mùa cuối cùng của một loạt phim truyền hình Mỹ thuộc thể loại kinh dị và hậu tận thế của kênh AMC, dựa trên seri truyện tranh cùng tên do Robert Kirkman, Tony Moore và Charlie Adlard sáng tạo. The Walking Dead - series khai sáng cho kỷ nguyên zombie trên màn ảnh nhỏ chuẩn bị đi tới hồi kết.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-14T00:00:00",
      "danhGia": 9,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
    {
      "maPhim": 10558,
      "tenPhim": "LIÊN MINH SIÊU THÚ DC 23",
      "biDanh": "lien-minh-sieu-thu-dc-23",
      "trailer": "https://www.youtube.com/watch?v=L2umMe5uRnk",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/lien-minh-sieu-thu-dc_gp01.jpg",
      "moTa": "Trong “Liên Minh Siêu Thú DC”, Siêu Cún Krypto và Superman là cặp bài trùng không thể tách rời, cùng sở hữu những siêu năng lực tương tự và cùng nhau chiến đấu chống lại tội phạm tại thành phố Metropolis. Khi Superman và những thành viên của Liên Minh Công Lý bị bắt cóc, Krypto phải thuyết phục cậu chàng Ace luộm thuộm, nàng Heo PB, Rùa Merton và Sóc Chip khai phá những sức mạnh tiềm ẩn và cùng nhau giải cứu các siêu anh hùng. “Liên Minh Siêu Thú DC” có sự góp giọng của bộ đôi ngôi sao nổi tiếng bậc nhất Hollywood Dwayne Johnson (lồng tiếng cho Siêu cún Krypto) và Kevin Hart (Superman). Đặc biệt, tài tử Keanu Reeves sẽ đảm nhận những câu thoại chất lừ đến từ Batman.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-10-24T19:07:24.247",
      "danhGia": 10,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
    {
      "maPhim": 10603,
      "tenPhim": "the waliking dead",
      "biDanh": "the-waliking-dead",
      "trailer": "https://www.youtube.com/watch?v=sfAc2U20uyg",
      "hinhAnh": "http://movieapi.cyberlearn.vn/hinhanh/the-waliking-dead_gp01.jpg",
      "moTa": "Xác Sống 11 (The Walking Dead Season 11) là mùa cuối cùng của một loạt phim truyền hình Mỹ thuộc thể loại kinh dị và hậu tận thế của kênh AMC, dựa trên seri truyện tranh cùng tên do Robert Kirkman, Tony Moore và Charlie Adlard sáng tạo. The Walking Dead - series khai sáng cho kỷ nguyên zombie trên màn ảnh nhỏ chuẩn bị đi tới hồi kết.",
      "maNhom": "GP01",
      "ngayKhoiChieu": "2022-05-14T00:00:00",
      "danhGia": 9,
      "hot": true,
      "dangChieu": true,
      "sapChieu": true
    },
],
};

export const FilmManageReducer = (state = initialState, action) => {
  switch (action.type) {
    case GET_LIST_BANNER:
      return {...state, listBanner: action.listBanner}
    default:
      return { ...state };
  }
};
