// Film manage
export const GET_LIST_BANNER = 'GET_LIST_BANNER';
export const GET_LIST_FILMS = 'GET_LIST_FILMS';
export const GET_INFOR_CINEMA = 'GET_INFOR_CINEMA';
export const GET_LIST_CINEMA_DETAIL = 'GET_LIST_CINEMA_DETAIL';
export const GET_FILM_DETAIL = 'GET_FILM_DETAIL';
export const LOGIN_ACTION = 'LOGIN_ACTION';